# Generated by Django 4.0.4 on 2022-05-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0003_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(upload_to='blog_image'),
        ),
    ]
