# Generated by Django 4.0.4 on 2022-05-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0007_topic_2_delete_content_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='body_2',
            field=models.TextField(blank=True),
        ),
    ]
