# Generated by Django 4.0.4 on 2022-05-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0008_topic_body_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
