# Generated by Django 4.0.4 on 2022-05-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0009_topic_title_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='body_2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_2',
        ),
    ]
