# Generated by Django 4.0.4 on 2022-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0010_remove_topic_body_2_remove_topic_title_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_2',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic_2',
            name='image2',
            field=models.ImageField(default=1, upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic_2',
            name='title2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
