# Generated by Django 4.0.4 on 2022-05-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0013_topic_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='body_2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='topic_2',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='topic_2',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='topic_2',
            name='title2',
        ),
    ]
