# Generated by Django 4.0.4 on 2022-05-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0014_remove_topic_body_2_remove_topic_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_2',
            old_name='body',
            new_name='body2',
        ),
        migrations.RenameField(
            model_name='topic_2',
            old_name='image',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='topic_2',
            old_name='title',
            new_name='title2',
        ),
    ]
