# Generated by Django 4.0.4 on 2022-06-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLE_app', '0016_rename_topic_2_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='body2',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='image2',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='title2',
            new_name='title',
        ),
    ]
